package edu.neu.coe.CSYE7200_Team6_2018Spring.Ingest

import org.apache.spark.sql.{Dataset, SparkSession}
import org.apache.spark.sql.types._


/**
  *  Created by team6 on 2018/3/19
  */

/**
  * The player format
  * (including player information and his/her one specific match information he/she was in and his/her performance in this match).
  *
  * @param date                 The date and time the match took place
  * @param game_size            The total number of teams that were in the game
  * @param match_id             The unique match id as generated by pubg.op.gg
  * @param match_mode           Whether the game was played in first-person (fpp) or third-person (tpp)
  * @param party_size           The maximum number of players per team. e.g 2 implies it was a duo queue match system
  * @param player_assists       Number of assists the player has scored
  * @param player_dbno          Number of knockdowns the player has scored
  * @param player_dist_ride     Total distance (in meters) that the player has travelled in a vehicle
  * @param player_dist_walk     Total distance (in meters) that the player has travelled on foot
  * @param player_dmg           Total Hitpoint that the player has dealt
  * @param player_kills         Number of kills the player has scored
  * @param player_name          Name of the player
  * @param player_survive_time  The survival time in seconds in this match
  * @param team_id              The team id that the player belonged to
  * @param team_placement       The final rank of the team within the match
  */
case class Player (date :String, game_size: Int, match_id: String, match_mode: String, party_size: Int,
                   player_assists: Int, player_dbno: Int, player_dist_ride: Double, player_dist_walk: Double,
                   player_dmg: Int, player_kills: Int, player_name: String, player_survive_time: Double,
                   team_id: Int, team_placement: Int)


object Player extends App{

  lazy val schema: StructType = new StructType(Array(StructField("date", StringType, true),
    StructField("game_size", IntegerType, true),
    StructField("match_id",StringType, true),
    StructField("match_mode", StringType, true),
    StructField("party_size", IntegerType, true),
    StructField("player_assists", IntegerType, true),
    StructField("player_dbno",IntegerType,true),
    StructField("player_dist_ride",DoubleType,true),
    StructField("player_dist_walk",DoubleType,true),
    StructField("player_dmg",IntegerType,true),
    StructField("player_kills",IntegerType,true),
    StructField("player_name",StringType,true),
    StructField("player_survive_time",DoubleType,true),
    StructField("team_id",IntegerType,true),
    StructField("team_placement",IntegerType,true))
  )


  lazy implicit val spark = {
    println("initial spark")
    SparkSession
      .builder()
      .appName("IngestRawToDataset")
      .master("local[*]")
      .getOrCreate()
  }
  /*
     To find encoder for type stored in a Dataset, Product types(case classes) are
     supported by importing spark.implicits._
  */
  import spark.implicits._
  class IngestPlayer extends Ingest{
    def ingest(srcDir: String, schema: StructType)(implicit spark:SparkSession): Dataset[Player] = {
      spark.read
        .option("header", "true")
        .option("inferSchema", "false")
        .schema(schema)
        .format("csv")
        .load(srcDir)
        .as[Player]
    }
    def filterPlayers(ds: Dataset[Player]): Dataset[Player] = {
      ds.filter(d => (d.player_dist_ride != 0 || d.player_dist_walk != 0) && d.player_survive_time <= 2400)
    }
  }

  object IngestPlayer extends IngestPlayer
  val ds = IngestPlayer.ingest("sample.csv", schema)
  ds.show()
}

